### ISSUE TITLE
No issue, just thanks!

### ISSUE THREAD

**Issue by reedstrm** [darkwater/bthome-logger#1]
I'm working on deploying a bunch of ATC temp/humidity sensors and esphome ble_proxies around my house, using HA to track them. Frustrated with mapping their visibility. There's always NFC Tools on the phone, but all I get there is the raw packet: was thinking "surely someone has made a simple app to read BTHome sensors directly". This logger will do! Dropped it on my laptop, and walked around a bit. Incidentally discovered that my laptop Bluetooth receiver/antenna sucks.

Anyway, thanks for the code!

**Comment by darkwater** [comment]
Glad to hear it helped you!

I realized I actually made an egui version too, but never pushed it to GitHub. I took a moment to make it work again and [published it here](https://github.com/darkwater/bthome-recv).
